### ISSUE TITLE
Not connecting to the hub

### ISSUE THREAD

**Issue by DGau20** [rogerio-faria/qdevops#1]
Hi Rogerio,
This project seems very promising.
I want to test it but no way to enter a valid command. 
I get ... not found! inaccessible Hub! Exiting...
I also tried with master.txt, but same result.
What is the syntax for the Qlik Sense Server?
Can we use Localhost?
Thanks

**Comment by rogerio-faria** [comment]
Thanks for the interest in this project. I'll do my best to keep this evolving.
Due the issue you created, I added a 'FAQ' folder to help with the connection, usually its a config problem.
[https://github.com/rogerio-faria/qdevops/tree/master/FAQ](https://github.com/rogerio-faria/qdevops/tree/master/FAQ) 
if that does not help. I'll be happy to connect to your machine (anydesk, teamview,etc...) and try to solve this issue. Contact me by email if you need: rogerioafaria@gmail.com

**Comment by DGau20** [comment]
Hi Rogerio,

Your Qdevops is good !
I just wonder how to interpret the result for measures and dimensions. We get some strange characters. What character set shall we use?
Thanks
Denis

**Comment by rogerio-faria** [comment]
Thanks DGau20, your msgs also help me to evolve qdevops.
Well we use a C# function File.ReadAllText and File.WriteAllText, these function "attempts to automatically detect the encoding of a file based on the presence of byte order marks. Encoding formats UTF-8 and UTF-32 (both big-endian and little-endian) can be detected." [check here](https://docs.microsoft.com/en-us/dotnet/api/system.io.file.readalltext?redirectedfrom=MSDN&view=netcore-3.1#System_IO_File_ReadAllText_System_String_). 

But thinking about that, I added an option for users to choose there encoding, example: 'utf-8', 'us-ascii', if blank will use the **System.Text.Encoding.Default**

Thanks

BTW, fell free to post more issues

**Comment by DGau20** [comment]
Hi Rogerio,

It would be great.
Where will we define the pagecode? Is it a command option?
I just tried to run a qvdevops -update, but i am still in version 3.0 even if it says 3.0 -> 3.1. 
Thanks
Denis

**Comment by rogerio-faria** [comment]
Sorry for the delay,
Well, about the version, is still paused. I fixed on site and int the app. But when running the commad will always update.
About the text enconding options, it's working on the commands: masterdims,mastermeasures,script

To get a good description, type
qdevops -h=<Command>
eg: qdevops-h=script

It will show a detailed command description, parameters and usage!

Cya

**Comment by DGau20** [comment]
Hi Rogerio,

That’s cool ! 
For the moment it asks for -update command, but once updated, then says trial expired. 
I will wait your update, no worries.

All the best.
Cheers
