### ISSUE TITLE
Comando Savesource não funciona somente com 1 comando

### ISSUE THREAD

**Issue by rafaelencinas1985** [rogerio-faria/qdevops#2]
Ao utilizar o comando :
>qdevops -u=desktop -savesource=c:\temp,**_s_**,"C:\XXX.qvf"

Não executa nenhuma ação. Foi detectado se utilizar "mais de um parâmetro" ele funciona, por exemplo

>qdevops -u=desktop -savesource=c:\temp,**_gs_**,"C:\XXX.qvf"

Obrigado.

**Comment by rogerio-faria** [comment]
Era um erro simples no índice do parâmetro, que foi corrigido e já foi atualizado!
