### ISSUE TITLE
Diretório Não localizado - SaveSource

### ISSUE THREAD

**Issue by rafaelencinas1985** [rogerio-faria/qdevops#3]
Se você utilizar uma barra no final do caminho do diretório tais como :
> qdevops.exe -u=desktop -savesource="c:\temp\qlik-script\\",

Ele diz que o diretório não existe, porém se você tirar a barra do final, funciona normalmente.

> qdevops.exe -u=desktop -savesource="c:\temp\qlik-script"

**Comment by rogerio-faria** [comment]
Rafael, não consegui reproduzir o erro, mas, de toda forma, coloquei uma instrução para tirar a última barra, se tiver.
