### ISSUE TITLE
Error getting connected

### ISSUE THREAD

**Issue by StephenDoherty** [rogerio-faria/qdevops#5]
Hello, I am unable to connect with the devops command line. I have followed the faq to create a new virtual proxy and i have tried many variations of the url (not putting the "/" at the end). I still get the following connection error. Any assistance would be appreciated. 

I should note also that I am on the server that this resides on.

"Location connected AsNtlmUserViaProxy!
Error using c:\users\adminsd\desktop\qdevops-master\servers\presperseqsconnection.txt: Unable to establish websocket connection.
Inaccessible Hub! Exiting..."

**Comment by rogerio-faria** [comment]
Hi Stephen,

Thanks for using qdevops.
The error you are getting is a generic error from the Qlik SDK.
I will update the FAQ session
Below, is a txt server file working sample: --> change only host,proxy,user,pass
proxy is the virtual proxy id in Qlik Sense Server

{
  "file": "prod.txt",
  "host": "https://prod.bi.com.br/",
  "proxy": "qdevops",
  "auth": "login",
  "user": "prodloc\\qlikuser",
  "pass": "pwd@123",
  "cert": "",
  "cert_pass": "",
  "ignorecert": "true",
  "useticket": "true",
  "ConfigFileType": "ServerConfig"
}

If still does not work, I'd like to assist you by anydesk or teamviewer, if possible. If not, can you send me the 'presperseqsconnection.txt' file ?
